version: '3'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    ports:
      - "9988:80"
    environment:
      USERNAME: webdav-user
      PASSWORD: paswrd
      LOCATION: /webdav/server
      AUTH_TYPE: Basic
    volumes:
      # - ./user.passwd:/user.passwd
      - /Users/sytolk/IdeaProjects/tagspaces-common/scripts/testContents:/var/lib/dav/data
